[package]
name = "psl"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.4.1"
unicode-ident = "1.0.12"
winnow = "0.6.13"

[dev-dependencies]
pretty_assertions = "1.4.0"
