[package]
name = "psl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.3.0"
unicode-ident = "1.0.12"
winnow = "0.5.17"

[dev-dependencies]
pretty_assertions = "1.4.0"
