on:
  pull_request:
    types: [opened, synchronize, reopened]

name: CI

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-setup@v1
      - env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo clippy \
            -q --message-format short \
            --workspace \
            -- -Dwarnings \
            2 > &1 \
            | reviewdog \
            -f=clippy \
            -name=clippy \
            -reporter=github-pr-review \
            -filter-mode=nofilter \
            -fail-on-error=true \
      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --workspace -- -Dwarnings
          fail_on_error: true
          filter_mode: nofilter
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: LLVM_PROFILE_FILE="grcov-%p-%m.profraw" RUSTFLAGS="-Cinstrument-coverage" cargo test
      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
