on:
  pull_request:
    types: [opened, synchronize, reopened]

name: CI

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-setup@v1
      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --workspace -- -Dwarnings
          fail_on_error: true
          filter_mode: nofilter
